name: "NetBox"
description: "IP address management (IPAM) and data center infrastructure management (DCIM) tool"
version: "1.0.0"
slug: "netbox"
arch:
  - aarch64
  - amd64
  - armv7
url: "https://github.com/TMA84/ha-addons"
startup: services
init: false
webui: http://[HOST]:[PORT:8000]/
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: NetBox Web Interface
ingress: true
map:
  - config:rw
options:
  superuser_name: "admin"
  superuser_email: "admin@example.com"
  superuser_password: "admin"
  secret_key: ""
  allowed_hosts: "*"
schema:
  superuser_name: str
  superuser_email: str
  superuser_password: str
  secret_key: str
  allowed_hosts: str
